version: '3.3'

services:
    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        user: pi
        environment:
            SA_PASSWORD: "IntegrationTest123!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - ./:/src
        command:
            - /bin/bash
            - -c
            - |
              /opt/mssql/bin/sqlservr & sleep 15
              /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P IntegrationTest123! -i /src/Otal.lmaoo.Data.IntegrationTests/Otal.lmaoo.Database_Create.sql
              sleep 30

    test:
        image: mcr.microsoft.com/dotnet/sdk:6.0
        user: pi
        volumes:
            - ./:/src
        environment:
            DB_DATABASE: "Otal.lmaoo.Database"
            DB_PASSWORD: "IntegrationTest123!"
            DB_SOURCE: "db"
        command:
          - /bin/bash
          - -c
          - |
            dotnet build /src/Otal.lmaoo.Data.IntegrationTests
            dotnet test /src/Otal.lmaoo.Data.IntegrationTests/Otal.lmaoo.Data.IntegrationTests.csproj --no-build --verbosity normal
        depends_on:
            - db
        links:
            - db