version: '3.9'

services:
    otal.lmaoo.web:
        build:
            context: .
            dockerfile: Otal.lmaoo.Web/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=${DOTNET_ENV}
            - ASPNETCORE_URLS=http://+:80
        ports:
            - "${DOTNET_PORT}:80"
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        environment:
            SA_PASSWORD: "${DB_PASSWORD}"
            ACCEPT_EULA: "Y"
        ports:
            - "${DB_PORT}:1433"
        volumes:
            - ./db_data:/var/opt/mssql/data
            - type: bind
              source: ./Otal.lmaoo.Data.IntegrationTests/Otal.lmaoo.Database_Create.sql
              target: /script/Otal.lmaoo.Database_Create.sql