name: Integration Test using Docker Compose

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: lmaoodev
    steps:
    - uses: actions/checkout@v2
    - run: | 
        sudo chown pi -R ./
    - name: Run container
      run: docker-compose -f docker-compose-Integration.yml up